version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - 'POSTGRES_USER=root'
      - 'POSTGRES_PASSWORD=password'
      - 'POSTGRES_DB=nextjs'
    ports:
      - '5432:5432'
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  minio:
    container_name: minio
    image: minio/minio:latest
    ports:
      - '9000:9000'
      - '9001:9001'
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: password
      MINIO_DEFAULT_BUCKETS: mybucket
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: password
      MINIO_REGION: eu-central-003
    volumes:
      - ./minio_data:/data
    command: server /data --console-address ":9001"
    networks:
      - minio-network

  createbuckets:
    container_name: createbuckets
    image: minio/mc
    depends_on:
      - minio
    entrypoint: >
      /bin/sh -c " /usr/bin/mc alias set myminio http://minio:9000 minio password; /usr/bin/mc mb myminio/mybucket; /usr/bin/mc anonymous set public myminio/mybucket; "
    networks:
      - minio-network

volumes:
  postgres_data:
  minio_data:

networks:
  minio-network:
    driver: bridge
