import React from 'react';
import {
  Award,
  Clapperboard,
  CookingPot,
  Disc3,
  Joystick,
  SatelliteDish,
  Shield,
  Sparkles,
  Tent,
  Volleyball,
  BookOpenText,
  Tablets,
  Circle,
  Gamepad,
  ListMusic,
  SquarePlay,
  Tv,
  Gamepad2,
  Shapes,
  Microwave,
  Vault,
  UtensilsCrossed,
  WashingMachine,
  ChefHat,
  SwatchBook,
  Refrigerator,
  Heater,
  Ratio,
  LandPlot,
  PlaneIcon,
  Fence,
  FlameKindling,
  MountainSnow,
  Hexagon,
  Waves,
  Sailboat,
  Presentation,
  Fan,
  Dumbbell,
  Printer,
  RadioTower,
  Flame,
  Warehouse,
  MapPinHouse,
  Phone,
  Anvil,
  PanelBottomDashed,
  CircleParking,
  AudioWaveform,
  Wifi,
  FireExtinguisher,
} from 'lucide-react';

export const iconsForAmenitiesGroup = {
  Entertainment: <Clapperboard />,
  'Kitchen & Dining': <CookingPot />,
  'Outdoor Features': <Tent />,
  'Pool & Spa Facilities': <Sparkles />,
  'Popular Amenities': <Award />,
  'Home Safety': <Shield />,
};

export const iconsForAmenitiesName = {
  'Satellite / Cable': <SatelliteDish />,
  Games: <Joystick />,
  Foosball: <Volleyball />,
  'DVD Player': <Disc3 />,
  Books: <BookOpenText />,
  'Ping Pong Table': <Tablets />,
  'Pool Table': <Circle />,
  'Game Room': <Gamepad />,
  'Music Library': <ListMusic />,
  'Video Library': <SquarePlay />,
  Television: <Tv />,
  'Video Games': <Gamepad2 />,
  Toys: <Shapes />,
  Stereo: <Microwave />,
  Oven: <Microwave />,
  Microwave: <Microwave />,
  Toaster: <Microwave />,
  'Coffee Maker': <Vault />,
  'Dishes & Utensils': <UtensilsCrossed />,
  Dishwasher: <WashingMachine />,
  Kitchen: <ChefHat />,
  Kitchenette: <ChefHat />,
  'Pantry Items': <SwatchBook />,
  Refrigerator: <Refrigerator />,
  Stove: <Heater />,
  'Deck / Patio': <Ratio />,
  Golf: <LandPlot />,
  'Lanai / Gazebo': <PlaneIcon />,
  'Lawn / Garden': <Fence />,
  'Outdoor Grill': <FlameKindling />,
  'Ski & Snowboard': <MountainSnow />,
  Tennis: <Hexagon />,
  'Water Sports Gear': <Waves />,
  Balcony: <Hexagon />,
  'Kayak / Canoe': <Sailboat />,
  Boat: <Sailboat />,
  'Private Pool': <Hexagon />,
  Sauna: <Hexagon />,
  'Indoor Pool': <Hexagon />,
  'Heated Pool': <Hexagon />,
  'Communal Pool': <Hexagon />,
  Jacuzzi: <Hexagon />,
  'Spa Whirlpool': <Hexagon />,
  Whirlpool: <Hexagon />,
  'Hot Tub': <Presentation />,
  'Air Conditioning': <Fan />,
  'Fitness Room / Equipment': <Dumbbell />,
  ' Fax': <Printer />,
  Internet: <RadioTower />,
  Fireplace: <Heater />,
  'Fireplace guards': <Heater />,
  'Wood Stove': <FlameKindling />,
  Garage: <Warehouse />,
  Elevator: <Hexagon />,
  'Living Room': <MapPinHouse />,
  Telephone: <Phone />,
  'Iron & Board': <Anvil />,
  'Hair Dryer': <PanelBottomDashed />,
  'Paid parking on premises': <CircleParking />,
  'Paid parking off premises': <CircleParking />,
  'Free street parking': <CircleParking />,
  'Free parking on premises': <CircleParking />,
  Parking: <CircleParking />,
  'Towels Provided': <Hexagon />,
  'Linens Provided': <Hexagon />,
  'Clothes Dryer': <Hexagon />,
  'Washing Machine': <WashingMachine />,
  Heating: <AudioWaveform />,
  'Free wifi': <Wifi />,
  'Fire extinguisher': <FireExtinguisher />,
};
