import { ReactQueryProviders } from '@/providers/react-query-provider';
import type { Metadata } from 'next';
import localFont from 'next/font/local';
import { NuqsAdapter } from 'nuqs/adapters/next/app';
import { Suspense } from 'react';
import { Footer } from './_components/footer';
import { Header } from './_components/header';
import './globals.css';

const geistSans = localFont({
  src: './fonts/GeistVF.woff',
  variable: '--font-geist-sans',
  weight: '100 900',
});
const geistMono = localFont({
  src: './fonts/GeistMonoVF.woff',
  variable: '--font-geist-mono',
  weight: '100 900',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <ReactQueryProviders>
        <body
          className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        >
          <Header />
          <NuqsAdapter>
            <Suspense
              fallback={
                <div
                  id='loading-screen'
                  className='fixed left-0 top-0 z-50 flex h-full w-full items-center justify-center bg-white opacity-75'
                >
                  <div className='h-12 w-12 animate-spin rounded-full border-8 border-solid border-purple-500 border-t-transparent' />
                </div>
              }
            >
              <main className='mx-auto mt-20'>{children}</main>
            </Suspense>
          </NuqsAdapter>
          <Footer />
        </body>
      </ReactQueryProviders>
    </html>
  );
}
