import type { Metadata } from 'next';

import { Footer } from './_components/footer';
import { Toaster } from '@/components/ui/toaster';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <main className='mx-auto min-h-screen py-20'>{children}</main>
      <Toaster />
      <Footer />
    </>
  );
}
