import type { Metadata } from 'next';
import { Suspense } from 'react';

import { Footer } from './_components/footer';
import { Header } from './_components/header';
import { Loader } from './_components/loader';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <Suspense fallback={<Loader />}>
      <Header />
      <main className='mx-auto min-h-screen py-20'>{children}</main>
      <Footer />
    </Suspense>
  );
}
